apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sysdig-agent
  labels:
    app: sysdig-agent
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sysdig-agent
    spec:
      volumes:
      - name: docker-sock
        hostPath:
         path: /var/run/docker.sock
      - name: dev-vol
        hostPath:
         path: /dev
      - name: proc-vol
        hostPath:
         path: /proc
      - name: boot-vol
        hostPath:
         path: /boot
      - name: modules-vol
        hostPath:
         path: /lib/modules
      - name: usr-vol
        hostPath:
          path: /usr
      - name: dshm
        emptyDir:
          medium: Memory
      - name: dragent-yaml
        configMap:
          name: sysdig-agent
          items:
            - key: dragent-yaml
              path: dragent.yaml
      hostNetwork: true
      hostPID: true
      containers:
      - name: sysdig-agent
        image: sysdig/agent:dev
        imagePullPolicy: Always
        securityContext:
         privileged: true
        env:
        - name: ACCESS_KEY
          value: 8c3a3eef-5f95-4937-bc72-f2bb9a48556a
#        - name: ADDITIONAL_CONF
#          value: "collector: localhost\ncollector_port: 30000\ndev_new_k8s: true"
#        resources:
#          requests:
#            cpu: 100m
#            memory: 512m
#          limits:
#            cpu: 200m
#            memory: 512m
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: docker-sock
          readOnly: false
        - mountPath: /host/dev
          name: dev-vol
          readOnly: false
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /opt/draios/etc/dragent.yaml
          name: dragent-yaml
          subPath: dragent.yaml
