kind: ReplicationController
apiVersion: v1
metadata:
  name: client
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    name: client
    role: clients
    app: demo
  template:
    spec:
      containers:
        - name: client
          image: ltagliamonte/recurling
          env:
          - name: URL
            value: http://10.0.0.47/{/,/wp-admin.php,/wp-login.php,/error1,/error2,/favicon.ico,/login.php,/wp-includes/js/jquery/jquery.jthemes/twentythirteen/images/headers/circle.png,/wp-content/themes/twentythirteen/style.css,/wp-includes/js/jquery/jquery-migrate.min.js,/wp-content/themes/twentythirteen/js/functions.js}
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: client
        role: clients
        app: demo
  labels:
    name: client-rc
    app: demo
