name: Driver build for test

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build-test:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Copy to local
        uses: ./.github/actions/build
        with:
          ssh_key: ${{ secrets.KEY_ONE }}
          hosts: ${{ secrets.HOSTS }}
          host_key_one: ${{ secrets.HOST_KEY_ONE }}
          host_key_two: ${{ secrets.HOST_KEY_TWO }}
          mode: "test"

      - name: Check version
        shell: bash
        run: |
          cd /tmp/kindling-falcolib-probe  
          # Checking .ko
          for version in ${{ vars.CHECKLIST_KO }};
          do
          {
            echo "Checking $version.ko"
            if [ ! -f $version.ko ]; then
              exit 1
            fi
          }
          done
          # Checking .o
          for file in ${{ vars.CHECKLIST_O }};
          do
          {
            echo "Checking $version.o"
            if [ ! -f $version.o ]; then
              exit 1
            fi
          }
          done
          echo "Pass test"