name: Sysdig Workflow Fossa
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Update Fossa Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run FOSSA scan
        uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
